'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { Activity, ArrowUpRight, Bot, CheckCircle2, Clock3, Download, Headphones, PhoneCall, Radio, Settings2, ShieldCheck, Users } from 'lucide-react'
import toast from 'react-hot-toast'
import { PageHeader } from '@/components/OmniPage'
import { ActionButton, api, DataState, MetricGrid, StatusBadge, Toolbar, downloadCsv } from '@/components/PlatformUI'

const formatDuration = (seconds = 0) => `${Math.floor(seconds / 60)}:${Math.floor(seconds % 60).toString().padStart(2, '0')}`
const dateValue = (value?: string) => { const result = value ? new Date(value).getTime() : 0; return Number.isNaN(result) ? 0 : result }
const formatDate = (value?: string) => value && dateValue(value) ? new Date(value).toLocaleString([], { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' }) : '—'

function VoiceMetric({ label, value, detail, icon: Icon }: { label: string; value: string | number; detail: string; icon: any }) {
  return <div className="surface-panel rounded-[20px] p-4"><div className="flex items-center justify-between"><span className="flex h-9 w-9 items-center justify-center rounded-lg border border-[#fed7aa] bg-[#fff7ed] text-[#d97706]"><Icon className="h-4 w-4" /></span><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-slate-400">Voice</span></div><div className="mt-4 text-xs font-semibold uppercase tracking-[.1em] text-slate-500">{label}</div><div className="mt-1 text-[1.7rem] font-extrabold tracking-[-.05em] text-slate-900">{value}</div><div className="mt-1 text-xs text-slate-500">{detail}</div></div>
}

function SectionTitle({ icon: Icon, title, action }: { icon: any; title: string; action?: React.ReactNode }) {
  return <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-lg bg-[#fff7ed] text-[#d97706]"><Icon className="h-3.5 w-3.5" /></span><h2 className="text-sm font-bold text-slate-900">{title}</h2></div>{action}</div>
}

export default function VoiceOverview() {
  const [stats, setStats] = useState<any>({})
  const [summary, setSummary] = useState<any>({})
  const [calls, setCalls] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const load = async () => {
    setLoading(true); setError('')
    try {
      const [statsPayload, summaryPayload, callsPayload] = await Promise.all([api('/api/calls/stats'), api('/api/omnichannel/summary'), api('/api/calls?limit=200')])
      setStats(statsPayload.data || {}); setSummary(summaryPayload.data || {}); setCalls(callsPayload.data || [])
    } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load voice overview') } finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])

  const activity = useMemo(() => { const days = Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setHours(0, 0, 0, 0); date.setDate(date.getDate() - (6 - index)); return { date, label: date.toLocaleDateString([], { weekday: 'short' }), count: 0 } }); calls.forEach((call) => { const timestamp = dateValue(call.call_date || call.created_at); const day = days.find((item) => item.date.toDateString() === new Date(timestamp).toDateString()); if (day) day.count += 1 }); return days }, [calls])
  const maxActivity = Math.max(...activity.map((item) => item.count), 1)
  const completed = Number(stats.completed_calls || stats.status_counts?.completed || 0)
  const missed = Number(stats.missed_calls || stats.status_counts?.missed || 0)
  const failed = Number(stats.failed_calls || stats.status_counts?.failed || 0)
  const transferred = Number(stats.human_transfers || 0)
  const aiHandled = Number(stats.ai_handled ?? Math.max(0, completed - transferred))
  const outcomes = [{ label: 'Completed', value: completed, color: 'bg-[#d97706]' }, { label: 'Missed', value: missed, color: 'bg-[#f09a36]' }, { label: 'Failed', value: failed, color: 'bg-[#e4687a]' }]
  const maxOutcome = Math.max(...outcomes.map((item) => item.value), 1)
  const recentCalls = [...calls].sort((a, b) => dateValue(b.call_date || b.created_at) - dateValue(a.call_date || a.created_at)).slice(0, 8)

  return <div className="space-y-6">
    <PageHeader title="Voice overview" description="See how your phone agent is answering, qualifying, transferring, and converting customer calls." actionLabel="View recordings" actionHref="/voice/calls" />
    <Toolbar onRefresh={load} onExport={() => downloadCsv('calls')}><ActionButton primary onClick={() => toast('Create a test lead and call it from Leads')} icon={<PhoneCall className="h-4 w-4" />}>Make test call</ActionButton><Link href="/voice/agent" className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3.5 text-sm font-medium text-slate-600 transition hover:bg-slate-50"><Settings2 className="h-4 w-4" />Agent settings</Link></Toolbar>
    <DataState loading={loading} error={error} onRetry={load}>
      <section className="relative overflow-hidden rounded-[24px] border border-[#fed7aa] bg-[linear-gradient(110deg,#fff7ed_0%,#ffffff_65%,#f8fafc_100%)] p-6 shadow-[0_16px_34px_rgba(15,23,42,.07)]"><div className="pointer-events-none absolute -right-10 -top-16 h-48 w-48 rounded-full bg-[#fed7aa]/40 blur-3xl" /><div className="relative flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.14em] text-[#b45309]"><Radio className="h-3.5 w-3.5" />Voice agent status</div><h2 className="mt-3 text-2xl font-extrabold tracking-[-.05em] text-slate-900">Your phone operation is ready to work.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{summary?.channels?.voice?.enabled ? 'Twilio is connected and calls are flowing through your AI agent.' : 'Connect your phone provider to start receiving and placing calls from the AI agent.'}</p></div><div className="flex flex-wrap items-center gap-2"><StatusBadge value={summary?.channels?.voice?.enabled ? 'Connected' : 'Not connected'} /><Link href="/voice/agent" className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3.5 text-sm font-semibold text-slate-600 transition hover:bg-slate-50">Configure agent <ArrowUpRight className="h-4 w-4" /></Link></div></div></section>

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><VoiceMetric label="Total calls" value={stats.total_calls || calls.length} detail={`${stats.calls_today || 0} today`} icon={PhoneCall} /><VoiceMetric label="Answered" value={completed} detail={`${stats.calls_this_week || 0} this week`} icon={CheckCircle2} /><VoiceMetric label="Missed" value={missed} detail="Calls needing follow-up" icon={Clock3} /><VoiceMetric label="AI handled" value={aiHandled} detail="Without human transfer" icon={Bot} /><VoiceMetric label="Human transfers" value={transferred} detail="Escalated to your team" icon={Users} /><VoiceMetric label="Leads generated" value={stats.leads_generated || 0} detail="From voice activity" icon={ShieldCheck} /></div>

      <div className="grid gap-5 xl:grid-cols-[1.45fr_1fr]"><section className="surface-panel rounded-[22px] p-5"><SectionTitle icon={Activity} title="Call activity" action={<span className="text-xs text-slate-400">Last 7 days</span>} /><div className="mt-6 flex h-52 items-end gap-3 border-b border-slate-100 px-2">{activity.map((item) => <div key={item.label} className="flex h-full flex-1 flex-col items-center justify-end gap-2"><div className="flex h-full w-full items-end justify-center"><div className="w-full max-w-10 rounded-t-lg bg-[linear-gradient(180deg,#f59e0b,#d97706)]" style={{ height: `${item.count ? Math.max(8, (item.count / maxActivity) * 100) : 3}%` }} /></div><span className="text-[11px] font-medium text-slate-400">{item.label}</span></div>)}</div><div className="mt-4 flex items-center justify-between text-xs text-slate-500"><span>Incoming and outgoing calls</span><span>{calls.length} loaded calls</span></div></section><section className="surface-panel rounded-[22px] p-5"><SectionTitle icon={Headphones} title="Call outcomes" action={<span className="text-xs text-slate-400">All calls</span>} /><div className="mt-6 space-y-5">{outcomes.map((item) => <div key={item.label}><div className="flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{item.label}</span><span className="font-bold text-slate-900">{item.value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${item.color}`} style={{ width: `${Math.max(item.value ? 8 : 2, (item.value / maxOutcome) * 100)}%` }} /></div></div>)}</div><div className="mt-6 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">Use missed calls and transfers as your follow-up queue. Open recordings to review the exact call context.</div></section></div>

      <section className="surface-panel overflow-hidden rounded-[22px]"><div className="border-b border-slate-200 p-5"><SectionTitle icon={PhoneCall} title="Recent calls" action={<Link href="/voice/calls" className="inline-flex items-center gap-1 text-xs font-semibold text-[#b45309] hover:underline">View all recordings <ArrowUpRight className="h-3.5 w-3.5" /></Link>} /></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-[.12em] text-slate-400"><tr><th className="px-5 py-3">Caller</th><th className="px-3 py-3">Direction</th><th className="px-3 py-3">Time</th><th className="px-3 py-3">Duration</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Open</th></tr></thead><tbody className="divide-y divide-slate-100">{recentCalls.map((call) => <tr key={call._id} className="transition hover:bg-slate-50"><td className="px-5 py-3"><div className="font-semibold text-slate-800">{call.lead?.name || call.phone_number || 'Unknown caller'}</div><div className="mt-0.5 text-xs text-slate-400">{call.lead?.company || call.phone_number || 'No contact details'}</div></td><td className="px-3 py-3 text-xs capitalize text-slate-500">{call.direction || 'outbound'}</td><td className="whitespace-nowrap px-3 py-3 text-xs text-slate-500">{formatDate(call.call_date || call.created_at)}</td><td className="px-3 py-3 text-xs text-slate-600">{formatDuration(call.duration)}</td><td className="px-3 py-3"><StatusBadge value={call.status || 'unknown'} /></td><td className="px-5 py-3 text-right"><Link href={`/voice/calls/${call._id}`} className="inline-flex h-8 items-center gap-1 rounded-md border border-slate-200 bg-white px-2.5 text-xs font-semibold text-slate-600 hover:bg-slate-50">Details <ArrowUpRight className="h-3 w-3" /></Link></td></tr>)}</tbody></table>{!recentCalls.length && <div className="px-5 py-12 text-center text-sm text-slate-500">Recent calls will appear here after the first call.</div>}</div></section>

      <div className="grid gap-5 lg:grid-cols-3"><section className="surface-panel rounded-[22px] p-5"><SectionTitle icon={Bot} title="AI agent" /><div className="mt-4 flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-3"><div><div className="text-sm font-semibold text-slate-800">Voice assistant</div><div className="mt-1 text-xs text-slate-500">{summary?.ai?.llm_provider || 'OpenAI'} reasoning layer</div></div><StatusBadge value={summary?.ai?.openai_ready ? 'Ready' : 'Needs setup'} /></div><Link href="/voice/agent" className="mt-4 inline-flex items-center gap-1 text-xs font-semibold text-[#b45309] hover:underline">Open agent settings <ArrowUpRight className="h-3.5 w-3.5" /></Link></section><section className="surface-panel rounded-[22px] p-5"><SectionTitle icon={ShieldCheck} title="Operations" /><div className="mt-4 space-y-3 text-sm"><div className="flex items-center justify-between"><span className="text-slate-500">Human handoff</span><StatusBadge value={summary?.operations?.human_handoff_enabled ? 'Enabled' : 'Disabled'} /></div><div className="flex items-center justify-between"><span className="text-slate-500">Agents ready</span><span className="font-bold text-slate-800">{summary?.operations?.human_agents_ready || 0}</span></div><div className="flex items-center justify-between"><span className="text-slate-500">Knowledge base</span><StatusBadge value={summary?.operations?.knowledge_base_enabled ? 'Ready' : 'Not ready'} /></div></div></section><section className="surface-panel rounded-[22px] p-5"><SectionTitle icon={Download} title="Next step" /><p className="mt-4 text-sm leading-6 text-slate-500">Review a recording, tune the voice agent, or test the full lead-capture flow.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/voice/calls" className="inline-flex h-9 items-center gap-2 rounded-md bg-[#d97706] px-3.5 text-sm font-semibold text-white hover:brightness-105">Review calls</Link><Link href="/leads" className="inline-flex h-9 items-center gap-2 rounded-md border border-slate-200 bg-white px-3.5 text-sm font-semibold text-slate-600 hover:bg-slate-50">Open leads</Link></div></section></div>
    </DataState>
  </div>
}
