'use client'

import { FormEvent, useEffect, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import toast from 'react-hot-toast'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { api } from '@/components/PlatformUI'

export default function AcceptInvitePage() {
  const router = useRouter(); const params = useSearchParams(); const token = params.get('token') || ''
  const [invite, setInvite] = useState<any>(null); const [form, setForm] = useState({ name: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { if (token) api<any>(`/api/auth/invite/${encodeURIComponent(token)}`).then((result) => { setInvite(result.data); setForm((current) => ({ ...current, name: result.data.name || '' })) }).catch((exception) => setError(exception instanceof Error ? exception.message : 'Invitation unavailable')) }, [token])
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); try { const result = await api<any>('/api/auth/accept-invite', { method: 'POST', body: JSON.stringify({ token, ...form }) }); window.localStorage.setItem('agentflow_token', result.data.token); toast.success('You joined the workspace'); router.replace('/') } catch (exception) { toast.error(exception instanceof Error ? exception.message : 'Unable to accept invitation') } finally { setLoading(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_top_left,#fff7ed_0%,#eef2f6_45%,#e7edf2_100%)] p-5"><div className="w-full max-w-[480px] rounded-[30px] border border-white/80 bg-white p-7 shadow-[0_24px_80px_rgba(15,23,42,.12)] sm:p-10"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#fff7ed] text-[#d97706]"><CheckCircle2 className="h-6 w-6" /></div><div className="mt-7 text-xs font-bold uppercase tracking-[.16em] text-[#b45309]">Workspace invitation</div>{error ? <><h1 className="mt-3 text-2xl font-extrabold text-slate-900">Invitation unavailable</h1><p className="mt-3 text-sm leading-6 text-slate-500">{error}</p></> : <><h1 className="mt-3 text-2xl font-extrabold text-slate-900">Join {invite?.workspace_name || 'your workspace'}</h1><p className="mt-3 text-sm leading-6 text-slate-500">You were invited as <span className="font-bold capitalize text-slate-700">{invite?.role || 'agent'}</span>{invite?.email ? ` · ${invite.email}` : ''}.</p><form onSubmit={submit} className="mt-7 space-y-4"><label><span className="field-label">Your name</span><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label><label><span className="field-label">Create password</span><input required minLength={8} type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} placeholder="At least 8 characters" /></label><button disabled={loading || !invite} className="mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#d97706] text-sm font-bold text-white disabled:opacity-50">{loading ? 'Joining...' : 'Accept invitation'}<ArrowRight className="h-4 w-4" /></button></form></>}</div></main>
}
